#grpc and rest both can access from same port 8080
server:
  port: 8080

grpc:
  server:
    #port: 9090
    enable-reflection: true # enable reflection test for local by postman

spring:
  datasource:
    url: jdbc:h2:mem:ordersdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

ai:
  mcp:
    server:
      name: order-service-mcp
      version: 1.0.0
      type: SYNC   # or ASYNC if you prefer reactive
      # Optional: customize SSE endpoints (defaults shown)
      sse-endpoint: /sse
      sse-message-endpoint: /mcp/message
      capabilities:
        tool: true
        resource: false
        prompt: false
        completion: false
